"""Initial migration

Revision ID: 73958e05b8c4
Revises: 704f186667ef
Create Date: 2025-03-27 22:46:34.214979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73958e05b8c4'
down_revision = '704f186667ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
